package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/Parnishkaspb/ozon_posts_graphql/internal/graph/model"
	servicepb "github.com/Parnishkaspb/ozon_posts_proto/gen/service/v1"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, login string, password string) (*model.AuthPayload, error) {
	answer, err := r.Auth.Login(ctx, &servicepb.LoginRequest{
		Login:    login,
		Password: password,
	})

	if err != nil {
		return &model.AuthPayload{}, err
	}

	return &model.AuthPayload{Token: answer.Token}, nil
}
