package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"time"

	"github.com/Parnishkaspb/ozon_posts_graphql/internal/graph/generated"
	helpergraph "github.com/Parnishkaspb/ozon_posts_graphql/internal/graph/helper"
	"github.com/Parnishkaspb/ozon_posts_graphql/internal/graph/model"
	"github.com/Parnishkaspb/ozon_posts_graphql/internal/helper"
	servicepb "github.com/Parnishkaspb/ozon_posts_proto/gen/service/v1"
)

// Author is the resolver for the author field.
func (r *commentResolver) Author(ctx context.Context, obj *model.Comment) (*model.User, error) {
	return helpergraph.ResolveAuthor(ctx, obj.AuthorID)
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, postID string, parentID *string, text string) (*model.Comment, error) {
	u, ok := helper.FromContext(ctx)

	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	var parentIDstring string
	if parentID != nil {
		parentIDstring = *parentID
	}

	resp, err := r.CommentSvc.CreateComment(ctx, &servicepb.CreateCommentRequest{
		PostId:   postID,
		AuthorId: u.ID.String(),
		ParentId: parentIDstring,
		Text:     text,
	})

	if err != nil {
		return nil, err
	}

	c := resp.GetComment()
	if c == nil {
		return nil, fmt.Errorf("empty comment in response")
	}

	pid := c.GetParentId()
	var pID *string
	if pid != "" {
		pID = &pid
	}

	createdAt := ""
	if ts := c.GetCreatedAt(); ts != nil {
		createdAt = ts.AsTime().UTC().Format(time.RFC3339)
	}

	comment := &model.Comment{
		ID:        c.GetId(),
		PostID:    c.GetPostId(),
		ParentID:  pID,
		Text:      c.GetText(),
		CreatedAt: createdAt,
		AuthorID:  c.GetAuthorId(),
	}

	r.SubSvc.Publish(comment.PostID, comment)

	return comment, nil
}

// Comment returns generated.CommentResolver implementation.
func (r *Resolver) Comment() generated.CommentResolver { return &commentResolver{r} }

type commentResolver struct{ *Resolver }
