package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"time"

	"github.com/Parnishkaspb/ozon_posts_graphql/internal/graph/generated"
	helpergraph "github.com/Parnishkaspb/ozon_posts_graphql/internal/graph/helper"
	"github.com/Parnishkaspb/ozon_posts_graphql/internal/graph/model"
	"github.com/Parnishkaspb/ozon_posts_graphql/internal/helper"
	servicepb "github.com/Parnishkaspb/ozon_posts_proto/gen/service/v1"
)

// Author is the resolver for the author field.
func (r *commentResolver) Author(ctx context.Context, obj *model.Comment) (*model.User, error) {
	return helpergraph.ResolveAuthor(ctx, obj.AuthorID)
}

// Replies is the resolver for the replies field.
func (r *commentResolver) Replies(ctx context.Context, obj *model.Comment, first int, after *string) (*model.CommentConnection, error) {
	req := &servicepb.GetCommentsRequest{
		PostId:   obj.PostID,
		ParentId: obj.ID,
		First:    int32(first),
	}
	if after != nil {
		req.After = *after
	}

	resp, err := r.CommentSvc.GetComments(ctx, req)
	if err != nil {
		return nil, err
	}

	edges := make([]*model.CommentEdge, 0, len(resp.GetComments()))
	for _, c := range resp.GetComments() {
		node := &model.Comment{
			ID:        c.GetId(),
			PostID:    c.GetPostId(),
			Text:      c.GetText(),
			CreatedAt: c.GetCreatedAt().AsTime().UTC().Format(time.RFC3339),
			AuthorID:  c.GetAuthorId(),
		}

		if c.GetParentId() != "" {
			pid := c.GetParentId()
			node.ParentID = &pid
		}

		edges = append(edges, &model.CommentEdge{
			Cursor: helpergraph.MakeCursor(c.GetCreatedAt(), c.GetId()),
			Node:   node,
		})
	}

	var endCursor *string
	if resp.GetEndCursor() != "" {
		c := resp.GetEndCursor()
		endCursor = &c
	}

	return &model.CommentConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			EndCursor:   endCursor,
			HasNextPage: resp.GetHasNextPage(),
		},
	}, nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, postID string, parentID *string, text string) (*model.Comment, error) {
	u, ok := helper.FromContext(ctx)

	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	var parentIDstring string
	if parentID != nil {
		parentIDstring = *parentID
	}

	resp, err := r.CommentSvc.CreateComment(ctx, &servicepb.CreateCommentRequest{
		PostId:   postID,
		AuthorId: u.ID.String(),
		ParentId: parentIDstring,
		Text:     text,
	})

	if err != nil {
		return nil, err
	}

	c := resp.GetComment()
	if c == nil {
		return nil, fmt.Errorf("empty comment in response")
	}

	pid := c.GetParentId()
	var pID *string
	if pid != "" {
		pID = &pid
	}

	createdAt := ""
	if ts := c.GetCreatedAt(); ts != nil {
		createdAt = ts.AsTime().UTC().Format(time.RFC3339)
	}

	comment := &model.Comment{
		ID:        c.GetId(),
		PostID:    c.GetPostId(),
		ParentID:  pID,
		Text:      c.GetText(),
		CreatedAt: createdAt,
		AuthorID:  c.GetAuthorId(),
	}

	r.SubSvc.Publish(comment.PostID, comment)

	return comment, nil
}

// CommentAdded is the resolver for the commentAdded field.
func (r *subscriptionResolver) CommentAdded(ctx context.Context, postID string) (<-chan *model.Comment, error) {
	ch := r.SubSvc.Subscribe(postID)

	go func() {
		<-ctx.Done()
		r.SubSvc.Unsubscribe(postID, ch)
	}()

	return ch, nil
}

// Comment returns generated.CommentResolver implementation.
func (r *Resolver) Comment() generated.CommentResolver { return &commentResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type commentResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
