package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"time"

	"github.com/Parnishkaspb/ozon_posts_graphql/internal/graph/generated"
	helpergraph "github.com/Parnishkaspb/ozon_posts_graphql/internal/graph/helper"
	"github.com/Parnishkaspb/ozon_posts_graphql/internal/graph/model"
	"github.com/Parnishkaspb/ozon_posts_graphql/internal/helper"
	servicepb "github.com/Parnishkaspb/ozon_posts_proto/gen/service/v1"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, text string, withoutComment *bool) (*model.Post, error) {
	u, ok := helper.FromContext(ctx)

	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	wc := false
	if withoutComment != nil {
		wc = *withoutComment
	}

	resp, err := r.PostSvc.CreatePost(ctx, &servicepb.CreatePostRequest{
		AuthorId:       u.ID.String(),
		Text:           text,
		WithoutComment: wc,
	})

	if err != nil {
		return nil, err
	}

	return &model.Post{
		ID:             resp.Post.Id,
		Text:           resp.Post.Text,
		WithoutComment: resp.Post.WithoutComment,
		CreatedAt:      resp.GetPost().GetCreatedAt().AsTime().Format(time.RFC3339),
		UpdatedAt:      resp.GetPost().GetUpdatedAt().AsTime().Format(time.RFC3339),
		AuthorID:       resp.Post.AuthorId,
	}, nil
}

// Author is the resolver for the author field.
func (r *postResolver) Author(ctx context.Context, obj *model.Post) (*model.User, error) {
	return helpergraph.ResolveAuthor(ctx, obj.AuthorID)
}

// Comments is the resolver for the comments field.
func (r *postResolver) Comments(ctx context.Context, obj *model.Post, first int, after *string) (*model.CommentConnection, error) {
	req := &servicepb.GetCommentsRequest{
		PostId:   obj.ID,
		ParentId: "",
		First:    int32(first),
	}
	if after != nil {
		req.After = *after
	}

	resp, err := r.CommentSvc.GetComments(ctx, req)
	if err != nil {
		return nil, err
	}

	edges := make([]*model.CommentEdge, 0, len(resp.GetComments()))
	for _, c := range resp.GetComments() {
		node := &model.Comment{
			ID:        c.GetId(),
			PostID:    c.GetPostId(),
			Text:      c.GetText(),
			CreatedAt: c.GetCreatedAt().AsTime().UTC().Format(time.RFC3339),
			AuthorID:  c.GetAuthorId(),
		}

		if c.GetParentId() != "" {
			pid := c.GetParentId()
			node.ParentID = &pid
		}

		edges = append(edges, &model.CommentEdge{
			Cursor: helpergraph.MakeCursor(c.GetCreatedAt(), c.GetId()),
			Node:   node,
		})
	}

	var endCursor *string
	if resp.GetEndCursor() != "" {
		c := resp.GetEndCursor()
		endCursor = &c
	}

	return &model.CommentConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			EndCursor:   endCursor,
			HasNextPage: resp.GetHasNextPage(),
		},
	}, nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, first int, after *string) (*model.PostConnection, error) {
	req := &servicepb.GetPostsRequest{
		First: int32(first),
	}
	if after != nil {
		req.After = *after
	}

	resp, err := r.PostSvc.GetPosts(ctx, req)
	if err != nil {
		return nil, err
	}

	posts := resp.GetPosts()

	edges := make([]*model.PostEdge, 0, len(posts))
	for _, p := range posts {
		node := &model.Post{
			ID:             p.GetId(),
			Text:           p.GetText(),
			WithoutComment: p.GetWithoutComment(),
			CreatedAt:      p.GetCreatedAt().AsTime().UTC().Format(time.RFC3339),
			UpdatedAt:      p.GetUpdatedAt().AsTime().UTC().Format(time.RFC3339),
			AuthorID:       p.GetAuthorId(),
		}

		edges = append(edges, &model.PostEdge{
			Cursor: helpergraph.MakeCursor(p.GetCreatedAt(), p.GetId()),
			Node:   node,
		})
	}

	var endCursor *string
	if c := resp.GetEndCursor(); c != "" {
		endCursor = &c
	}

	return &model.PostConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			EndCursor:   endCursor,
			HasNextPage: resp.GetHasNextPage(),
		},
	}, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*model.Post, error) {
	resp, err := r.PostSvc.GetPost(ctx, &servicepb.GetPostRequest{Id: id})
	if err != nil {
		return nil, err
	}
	p := resp.GetPost()
	if p == nil {
		return nil, nil
	}

	return &model.Post{
		ID:             p.GetId(),
		Text:           p.GetText(),
		WithoutComment: p.GetWithoutComment(),
		CreatedAt:      p.GetCreatedAt().AsTime().UTC().Format(time.RFC3339),
		UpdatedAt:      p.GetUpdatedAt().AsTime().UTC().Format(time.RFC3339),
		AuthorID:       p.GetAuthorId(),
	}, nil
}

// Post returns generated.PostResolver implementation.
func (r *Resolver) Post() generated.PostResolver { return &postResolver{r} }

type postResolver struct{ *Resolver }
