package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"log"
	"time"

	"github.com/Parnishkaspb/ozon_posts_graphql/internal/graph/generated"
	helpergraph "github.com/Parnishkaspb/ozon_posts_graphql/internal/graph/helper"
	"github.com/Parnishkaspb/ozon_posts_graphql/internal/graph/model"
	"github.com/Parnishkaspb/ozon_posts_graphql/internal/helper"
	servicepb "github.com/Parnishkaspb/ozon_posts_proto/gen/service/v1"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, text string, withoutComment *bool) (*model.Post, error) {
	u, ok := helper.FromContext(ctx)

	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	wc := false
	if withoutComment != nil {
		wc = *withoutComment
	}

	resp, err := r.PostSvc.CreatePost(ctx, &servicepb.CreatePostRequest{
		AuthorId:       u.ID.String(),
		Text:           text,
		WithoutComment: wc,
	})

	if err != nil {
		log.Printf("ERROR: %+v", err)
		return nil, err
	}

	log.Printf("POST: %+v", resp)

	return &model.Post{
		ID:             resp.Post.Id,
		Text:           resp.Post.Text,
		WithoutComment: resp.Post.WithoutComment,
		CreatedAt:      resp.GetPost().GetCreatedAt().AsTime().Format(time.RFC3339),
		UpdatedAt:      resp.GetPost().GetUpdatedAt().AsTime().Format(time.RFC3339),
		AuthorID:       resp.Post.AuthorId,
	}, nil
}

// Author is the resolver for the author field.
func (r *postResolver) Author(ctx context.Context, obj *model.Post) (*model.User, error) {
	return helpergraph.ResolveAuthor(ctx, obj.AuthorID)
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context) ([]*model.Post, error) {
	resp, err := r.PostSvc.GetPosts(ctx, &servicepb.GetPostsRequest{})
	if err != nil {
		return nil, err
	}

	result := make([]*model.Post, 0, len(resp.GetPosts()))
	for _, p := range resp.GetPosts() {
		result = append(result, &model.Post{
			ID:             p.GetId(),
			Text:           p.GetText(),
			WithoutComment: p.GetWithoutComment(),
			CreatedAt:      p.GetCreatedAt().AsTime().Format(time.RFC3339),
			UpdatedAt:      p.GetUpdatedAt().AsTime().Format(time.RFC3339),
			AuthorID:       p.GetAuthorId(),
		})
	}
	return result, nil
}

// PostID is the resolver for the postID field.
func (r *queryResolver) PostID(ctx context.Context, id string) (*model.Post, error) {
	resp, err := r.PostSvc.GetPosts(ctx, &servicepb.GetPostsRequest{
		Ids: []string{id},
	})
	if err != nil {
		return nil, err
	}

	posts := resp.GetPosts()
	if len(posts) == 0 {
		return nil, fmt.Errorf("post not found")
	}

	p := posts[0]

	return &model.Post{
		ID:             p.GetId(),
		Text:           p.GetText(),
		WithoutComment: p.GetWithoutComment(),
		CreatedAt:      p.GetCreatedAt().AsTime().Format(time.RFC3339),
		UpdatedAt:      p.GetUpdatedAt().AsTime().Format(time.RFC3339),
		AuthorID:       p.GetAuthorId(),
	}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Post returns generated.PostResolver implementation.
func (r *Resolver) Post() generated.PostResolver { return &postResolver{r} }

type mutationResolver struct{ *Resolver }
type postResolver struct{ *Resolver }
