package graph

import (
	"context"
	"github.com/Parnishkaspb/ozon_posts_graphql/internal/graph/generated"
	"github.com/Parnishkaspb/ozon_posts_graphql/internal/graph/model"
)

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

type subscriptionResolver struct{ *Resolver }

func (r *Resolver) Subscription() generated.SubscriptionResolver {
	return &subscriptionResolver{r}
}

func (r *subscriptionResolver) CommentAdded(ctx context.Context, postID string) (<-chan *model.Comment, error) {
	ch := r.SubSvc.Subscribe(postID)

	go func() {
		<-ctx.Done()
		r.SubSvc.Unsubscribe(postID, ch)
	}()

	return ch, nil
}
