package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/Parnishkaspb/ozon_posts_graphql/internal/graph/generated"
	"github.com/Parnishkaspb/ozon_posts_graphql/internal/graph/model"
	servicepb "github.com/Parnishkaspb/ozon_posts_proto/gen/service/v1"
)

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	resp, err := r.UserSvc.GetUsers(ctx, &servicepb.GetUsersRequest{})

	if err != nil {
		return nil, err
	}
	users := resp.Users

	result := make([]*model.User, len(users))
	for i, user := range users {
		result[i] = &model.User{
			ID:      user.Id,
			Name:    user.Name,
			Surname: user.Surname,
		}
	}
	return result, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
