// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Token string `json:"token"`
}

type Mutation struct {
}

type Post struct {
	ID             string `json:"id"`
	Text           string `json:"text"`
	WithoutComment bool   `json:"withoutComment"`
	CreatedAt      string `json:"createdAt"`
	UpdatedAt      string `json:"updatedAt"`
	AuthorID       string `json:"authorId"`
	Author         *User  `json:"Author"`
}

type Query struct {
}

type User struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Surname string `json:"surname"`
}
