// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Token string `json:"token"`
}

type Comment struct {
	ID        string  `json:"id"`
	PostID    string  `json:"postId"`
	ParentID  *string `json:"parentId,omitempty"`
	Text      string  `json:"text"`
	CreatedAt string  `json:"createdAt"`
	AuthorID  string  `json:"authorId"`
	Author    *User   `json:"author"`
}

type Mutation struct {
}

type Post struct {
	ID             string `json:"id"`
	Text           string `json:"text"`
	WithoutComment bool   `json:"withoutComment"`
	CreatedAt      string `json:"createdAt"`
	UpdatedAt      string `json:"updatedAt"`
	AuthorID       string `json:"authorId"`
	Author         *User  `json:"author"`
}

type Query struct {
}

type User struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Surname string `json:"surname"`
}
